version: '3.8'
services:
  web-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      # setup file or folder public
      - ../assets:/usr/share/nginx/html/assets
networks:
  default:
    name: nginx_default
    external: true